CC = gcc

packet.o: packet.c packet.h
	gcc -c packet.c -o packet.o

generic_packet.o: generic_packet.c generic_packet.h
	gcc generic_packet.c -c
	
connect_packet.o: connect_packet.c connect_packet.h
	gcc connect_packet.c -c
	
chat_packet.o: chat_packet.c chat_packet.h
	gcc chat_packet.c -c
